/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIOxDriver.h"
#include "PwmDriver.h"
#include "BasicTimer.h"
#include "USARTxDriver.h"

// Handlers PWM
GPIO_Handler_t pinPWM_handler ={0};
PWM_Handler_t PWM_handler = {0};

// Handlers transmisión USART
GPIO_Handler_t PinTX_handler = {0};
GPIO_Handler_t PinRX_handler = {0};
USART_Handler_t USART2_handler = {0};

// Handlers blinky led
BasicTimer_Handler_t timerLed = {0};
GPIO_Handler_t blinkyLed = {0};

/* Variables */
char data_recibida_USART2 = 0;
uint16_t valor_Dutty = 1500;
char mensaje[128];

// Funciones a utilizar
void inicializacion_PWM(void);
void inicializacion_pines_USART(void);
void inicializacion_Led_Estado(void);


int main(void)
{
	inicializacion_Led_Estado();
	inicializacion_PWM();
	inicializacion_pines_USART();
	startPwmSignal(&PWM_handler);

    /* Loop forever */
	while(1){
		if(data_recibida_USART2 != '\0') {

			if(data_recibida_USART2 == 'D'){
				valor_Dutty -= 10;
				updateDuttyCycle(&PWM_handler, valor_Dutty);
			}
			if(data_recibida_USART2 == 'E'){
				valor_Dutty += 10;
				updateDuttyCycle(&PWM_handler, valor_Dutty);
			}

			/* Imprimir mensaje */
			sprintf(mensaje, "dutty = %u \n", (unsigned int)valor_Dutty);
			writeWord(&USART2_handler, mensaje);

			data_recibida_USART2 = '\0';
		}



	}

	return 0;
}

void inicializacion_PWM(void){
	pinPWM_handler.pGPIOx = GPIOB;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinNumber = PIN_5;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinOType = GPIO_OTYPE_PUSHPULL;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OSPEED_FAST;
	pinPWM_handler.GPIO_PinConfig.GPIO_PinAltFunMode = AF2;
	GPIO_Config(&pinPWM_handler);

	PWM_handler.ptrTIMx = TIM3;
	PWM_handler.config.channel = PWM_CHANNEL_2;
	PWM_handler.config.periodo = 20000;
	PWM_handler.config.prescaler = 16; /* Incremento cada microsegundo */
	PWM_handler.config.duttyCicle = valor_Dutty;
	pwm_Config(&PWM_handler);

}

/* Pines A2 y A3 */
void inicializacion_pines_USART(void){

	// Para realizar transmisión por USB se utilizan los pines PA2 (TX) y PA3 (RX)
	// Inicializacion de PIN A2 con funcion alternativa de USART2
	PinTX_handler.pGPIOx = GPIOA;
	PinTX_handler.GPIO_PinConfig.GPIO_PinNumber = PIN_2;
	PinTX_handler.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	PinTX_handler.GPIO_PinConfig.GPIO_PinAltFunMode = AF7;
	GPIO_Config(&PinTX_handler);

	// Inicialización de PIN A3 con función alternativa de USART2
	PinRX_handler.pGPIOx = GPIOA;
	PinRX_handler.GPIO_PinConfig.GPIO_PinNumber = PIN_3;
	PinRX_handler.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	PinRX_handler.GPIO_PinConfig.GPIO_PinAltFunMode = AF7;
	GPIO_Config(&PinRX_handler);

	// Inicialización de módulo serial USART2 transmisión + recepción e interrupción RX
	USART2_handler.ptrUSARTx = USART2;
	USART2_handler.USART_Config.USART_mode = USART_MODE_RXTX;
	USART2_handler.USART_Config.USART_baudrate = USART_BAUDRATE_9600;
	USART2_handler.USART_Config.USART_datasize = USART_DATASIZE_8BIT;
	USART2_handler.USART_Config.USART_parity = USART_PARITY_NONE;
	USART2_handler.USART_Config.USART_stopbits = USART_STOPBIT_1;
	USART2_handler.USART_Config.USART_enableIntRX = USART_INTERRUPT_RX_ENABLE;
	USART2_handler.USART_Config.USART_enableIntTX = USART_INTERRUPT_TX_NONE;
	USART_Config(&USART2_handler);
}

/* Pin A5 */
void inicializacion_Led_Estado(void){
	// Timer para LED de estado usando el LED2
	timerLed.ptrTIMx = TIM2;
	timerLed.TIMx_Config.TIMx_mode	= BTIMER_MODE_UP;
	timerLed.TIMx_Config.TIMx_speed = BTIMER_SPEED_1ms;
	timerLed.TIMx_Config.TIMx_period = 300; // Tiempo en milisegundos
	timerLed.TIMx_Config.TIMx_interruptEnable = 1; // Activar interrupción
	BasicTimer_Config(&timerLed);

	// Controlador de LED2 asignado como led de estado
	blinkyLed.pGPIOx = GPIOA;
	blinkyLed.GPIO_PinConfig.GPIO_PinNumber = PIN_5;
	blinkyLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	blinkyLed.GPIO_PinConfig.GPIO_PinOType = GPIO_OTYPE_PUSHPULL;
	blinkyLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	blinkyLed.GPIO_PinConfig.GPIO_PinAltFunMode = AF0;
	GPIO_Config(&blinkyLed);
}

/* Centelleo led de estado */
void BasicTimer2_Callback(void){
	GPIOxTooglePin(&blinkyLed);
}

/* Interrupción por recepción USART */
void callback_USART2_RX(void){
	data_recibida_USART2 = get_data_RX();
}

